---
- name: Add nginx stable PPA repository
  apt_repository: repo='ppa:nginx/stable'
  when: ansible_lsb.id == "Ubuntu"
  tags:
    - install
    - deps
    - web-server

- name: Install nginx
  apt:  pkg={{ item }}
        state=latest
        update_cache=yes
  with_items:
    - nginx
    - nginx-extras
  tags:
    - web-server
    - deps

- name: Install default nginx configuration
  template: src=nginx-default.conf
            dest=/etc/nginx/nginx.conf
            owner=root
            group=root
            mode=0644
  notify:
    - reload-nginx
  tags:
    - web-server

- name: Disable default website
  file: state=absent
        dest=/etc/nginx/sites-enabled/default
  notify:
    - reload-nginx
  tags:
    - web-server

- name: Create www root directory
  file: state=directory
        dest={{ web_root }}/{{ hostname }}
        owner={{ web_user }}
        group={{ web_user }}
        mode=0755
  tags:
    - web-server

- name: Install backend nginx configuration
  template: src=backend-nginx.conf
            dest=/etc/nginx/sites-available/{{ hostname }}
            owner=root
            group=root
            mode=0644
  notify:
    - reload-nginx
  tags:
    - web-server

- name: Enable backend website
  file: state=link
        src=/etc/nginx/sites-available/{{ hostname }}
        dest=/etc/nginx/sites-enabled/{{ hostname }}
        owner=root
        group=root
  tags:
    - web-server

- name: Install local nginx configuration
  copy: src=nginx-local.conf
        dest=/etc/nginx/conf.d/nginx-local.conf
        owner=root
        group=root
        mode=0644
  notify:
    - reload-nginx
  tags:
    - web-server

- name: Install backend special nginx configuration
  copy: src=nginx-backend.conf
        dest=/etc/nginx/conf.d/nginx-backend.conf
        owner=root
        group=root
        mode=0644
  notify:
    - reload-nginx
  tags:
    - web-server

- name: Install nginx upstream definitions
  template: src=backend-upstreams.conf
            dest=/etc/nginx/conf.d/backend-upstreams.conf
            mode=0644
            owner=root
            group=root
  notify:
    - reload-nginx
  tags:
    - web-server

- name: Does the nginx custom directory exists?
  file: path=/etc/nginx/custom/
        state=directory
        owner=root
        group=root
  notify:
    - reload-nginx
  tags:
    - web-server

- name: Copy backend maintenance configuration
  copy: src=backend-maintenance.conf
        dest=/etc/nginx/custom/backend-maintenance.conf
        owner=root
        group=root
        mode=0644
  notify:
    - reload-nginx
  tags:
    - web-server

- name: Copy backend proxy cache configuration
  copy: src=backend-proxy-cache.conf
        dest=/etc/nginx/custom/backend-proxy-cache.conf
        owner=root
        group=root
        mode=0644
  notify:
    - reload-nginx
  tags:
    - web-server

- name: Copy backend proxy configuration
  copy: src=backend-proxy.conf
        dest=/etc/nginx/custom/backend-proxy.conf
        owner=root
        group=root
        mode=0644
  notify:
    - reload-nginx
  tags:
    - web-server

- name: Copy maintenance page
  copy: src=maintenance.html
        dest={{ web_root }}/{{ hostname }}/maintenance.html.not
        owner={{ app_user }}
        group={{ app_user }}
        mode=0644
  tags:
      - web-server

- name: Copy maintenance page art
  copy: src=kernelci-maintenance.svg
        dest={{ web_root }}/{{ hostname }}/kernelci-maintenance.svg
        owner={{ app_user }}
        group={{ app_user }}
        mode=0644
  tags:
      - web-server