---

- name: Install Upstart conf
  template: src=kernel-ci-backend.conf
            dest=/etc/init/{{ upstart_service }}.conf
            mode=0644
            owner=root
            group=root

- name: Install celery upstart configuration
  template: src=celery.conf
            dest=/etc/init/celery.conf
            owner=root
            group=root
            mode=0644
