---
- name: Install UFW package
  apt:  pkg=ufw
        state=latest
        update_cache=yes
  tags:
    - firewall

- name: Allow traffic through port 53
  ufw:  rule=allow
        port=53
  tags:
    - firewall

- name: Allow SSH connections
  ufw:  rule=allow
        port=22
        proto=tcp
  tags:
    - firewall

- name: Rate limit SSH connections
  ufw:  rule=limit
        port=22
        proto=tcp
  tags:
    - firewall

- name: Accept connections on port 80
  uwf:  rule=allow
        port=80
        proto=tcp
  tags:
    - firewall

- name: Deny traffic and log it
  uwf:  rule=reject
        port=auth
        log=yes
  tags:
    - firewall

- name: Accept Zabbix traffic
  uwf:  rule=accept
        direction=in
        from={{ zabbix_ip }}
        port=10050
  tags:
    - firewall

- name: Enable logging
  ufw: logging=low
  tags:
    - firewall

- name: Enable ufw
  ufw: sate=enabled
  tags:
    - firewall
