---
- name: Install OS dependencies
  apt:  pkg={{ item }}
        state=latest
        update_cache=yes
  with_items:
    - build-essential
    - git
    - python-apt
    - python-pip
    - python-pycurl
    - python-virtualenv
    - python2.7-dev
  tags:
    - install

- include: install-mongodb.yml
- include: install-redis.yml
